language: scala

scala:
  - 2.11.7

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

services:
  - docker

before_install:
  - chmod +x script/deploy.sh

script:
  - sbt clean scalastyle test compile

after_success:
  - ./script/deploy.sh