language: scala

scala:
  - 2.11.7

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

services:
  - docker

script:
  - sbt clean scalastyle test compile

after_success:
  - cd ../ && ./script/deploy.sh